### ISSUE TITLE
Bootloop Rn8pro begonia

### ISSUE THREAD

**Issue by jhay06** [timjosten/mtk_imei#10]
When i flash this my device became unbootable , it boots but as soon as MIUI appears , it restart then it boot to recovery , 

Im using stock rom miui , it happens on all of stock rom , from 9 to 11 , but it works when i install a custom rom

**Comment by timjosten** [comment]
Use 12.5.8 global rom

**Comment by jhay06** [comment]
i see , 12.5.8 rom , i downloaded 12.5.6 rom , thanks for this  

anyways for lower android version ?

**Comment by timjosten** [comment]
> anyways for lower android version ?

someone else has to build a kernel module for it, that's about it

**Comment by timjosten** [comment]
> anyways for lower android version ?

https://github.com/timjosten/mtk_imei/commit/228134d43c4473cedc4021408941aa0335c70006
