### ISSUE TITLE
Add support request #1

### ISSUE THREAD

**Issue by postcumer** [timjosten/mtk_imei#11]
Issue created for the reason of asking to add support for device Xiaomi Redmi Note 12 Pro 5G/Pro+ 5G/Discovery equipped with Mediatek Dimensity 1080.

(I don't know how this goes on GitHub to ask for support for a random device but i thought let's try least. You can contact me if you can consider this request I'll co-operate with you in all ways.)

Contact -
Telegram - @postcumer
Email - tambolireehan@gmail.com

**Comment by timjosten** [comment]
contacted in tg

**Comment by jillibilli** [comment]
will 5G phones be supported?
I need to replace my broken phone and I would like to get one that works with mtk_imei and is as future proof as possible.

I was under the impression that hydra might be using mtk_imei for imei repairing, but then I saw that hydra supports imei repairing on Xiaomi Redmi Note 12 Pro Plus (ruby) https://www.hydradongle.com/devices/brand/model/6866  which has 5G

contact:
email: jillibilli@proton.me
(no tg for now)
